00. PyTorch Fundamentals Exercises

In [80]:
import torch

a_tensor = torch.rand(7, 7)
a_tensor

tensor([[0.8549, 0.5509, 0.2868, 0.2063, 0.4451, 0.3593, 0.7204],
        [0.0731, 0.9699, 0.1078, 0.8829, 0.4132, 0.7572, 0.6948],
        [0.5209, 0.5932, 0.8797, 0.6286, 0.7653, 0.1132, 0.8559],
        [0.6721, 0.6267, 0.5691, 0.7437, 0.9592, 0.3887, 0.2214],
        [0.3742, 0.1953, 0.7405, 0.2529, 0.2332, 0.9314, 0.9575],
        [0.5575, 0.4134, 0.4355, 0.7369, 0.0331, 0.0914, 0.8994],
        [0.9936, 0.4703, 0.1049, 0.5137, 0.2674, 0.4990, 0.7447]])

In [81]:
b_tensor = torch.rand(1, 7)
print(b_tensor)

torch.mm(a_tensor, b_tensor.T)

tensor([[0.7213, 0.4414, 0.5550, 0.6361, 0.1081, 0.3305, 0.5196]])


tensor([[1.6914],
        [1.7581],
        [2.0906],
        [1.8975],
        [1.7585],
        [1.7961],
        [1.8900]])

In [82]:
RANDOM_SEED = 42

torch.manual_seed(RANDOM_SEED)
a_tensor = torch.rand(7, 7)
print(a_tensor)

torch.manual_seed(RANDOM_SEED)
b_tensor = torch.rand(1, 7)
print(b_tensor)

torch.mm(a_tensor, b_tensor.T)

tensor([[0.8823, 0.9150, 0.3829, 0.9593, 0.3904, 0.6009, 0.2566],
        [0.7936, 0.9408, 0.1332, 0.9346, 0.5936, 0.8694, 0.5677],
        [0.7411, 0.4294, 0.8854, 0.5739, 0.2666, 0.6274, 0.2696],
        [0.4414, 0.2969, 0.8317, 0.1053, 0.2695, 0.3588, 0.1994],
        [0.5472, 0.0062, 0.9516, 0.0753, 0.8860, 0.5832, 0.3376],
        [0.8090, 0.5779, 0.9040, 0.5547, 0.3423, 0.6343, 0.3644],
        [0.7104, 0.9464, 0.7890, 0.2814, 0.7886, 0.5895, 0.7539]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593, 0.3904, 0.6009, 0.2566]])


tensor([[3.2618],
        [3.4084],
        [2.4866],
        [1.4525],
        [1.7079],
        [2.7291],
        [2.9204]])

In [83]:
torch.cuda.manual_seed_all(1234)
print(torch.cuda.initial_seed())

1234


In [84]:
torch.manual_seed(42)
a_tensor = torch.rand(2, 3)
torch.manual_seed(42)
b_tensor = torch.rand(2, 3)
device = "cuda" if torch.cuda.is_available() else "cpu"
a_tensor = a_tensor.to(device)
b_tensor = b_tensor.to(device)
print(a_tensor, "\n", b_tensor)

tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009]], device='cuda:0') 
 tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009]], device='cuda:0')


In [85]:
result_mul = torch.mm(a_tensor, b_tensor.T)
result_mul, result_mul.shape, result_mul.device

(tensor([[1.7622, 1.4337],
         [1.4337, 1.4338]], device='cuda:0'),
 torch.Size([2, 2]),
 device(type='cuda', index=0))

In [86]:
torch.max(result_mul), torch.min(result_mul)

(tensor(1.7622, device='cuda:0'), tensor(1.4337, device='cuda:0'))

In [87]:
torch.argmax(result_mul), torch.argmin(result_mul)

(tensor(0, device='cuda:0'), tensor(1, device='cuda:0'))

In [88]:
torch.manual_seed(7)
tensor = torch.rand(1, 1, 1, 10)
tensor, tensor.shape, torch.squeeze(tensor), torch.squeeze(tensor).shape

(tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
            0.3653, 0.8513]]]]),
 torch.Size([1, 1, 1, 10]),
 tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
         0.8513]),
 torch.Size([10]))